# Python

In [103]:
import pandas as pd
import numpy as np

In [104]:
df = pd.read_csv("./test.csv")
df.head()

x          y
0  77  79.775152
1  21  23.177279
2  22  25.609262
3  20  17.857388
4  36  41.849864

In [105]:
x = df["x"].values.reshape(-1,1)
y = df["y"].values

In [106]:
import linear_regression
import imp
imp.reload(linear_regression)

<module 'linear_regression' from 'C:\\Users\\1004\\공부\\Python for ML\\Linear Regression\\Linear Regression - Assignment (Normal Equation)\\linear_regression.py'>

In [107]:
lr = linear_regression.LinearRegression()

In [108]:
lr.fit(x,y)

In [109]:
lr.intercept

-0.4618107736611705

In [110]:
lr.coef

array([1.01433536])

In [111]:
lr.predict(X)[:10]

array([77.64201157, 20.83923168, 21.85356704, 19.82489633, 36.05426201,
       14.75321955, 62.42698124, 95.90004796, 19.82489633,  4.609866  ])

# Sklearn

In [112]:
from sklearn import linear_model
sk_lr = linear_model.LinearRegression(normalize=False)
sk_lr.fit(x,y)

LinearRegression()

In [113]:
sk_lr.intercept_

-0.4618107736611776

In [114]:
import numpy.testing as npt
npt.assert_almost_equal(sk_lr.intercept_, lr.intercept)

In [115]:
sk_lr.coef_

array([1.01433536])

In [116]:
sk_lr.predict(x)[:5]

array([77.64201157, 20.83923168, 21.85356704, 19.82489633, 36.05426201])

# multiple variables

In [117]:
df = pd.read_csv("./mlr09.csv")
df.head()

height_in_feet  weight_in_pounds  successful_field_goals  \
0             6.8               225                   0.442   
1             6.3               180                   0.435   
2             6.4               190                   0.456   
3             6.2               180                   0.416   
4             6.9               205                   0.449   

   percent_of_successful_free_throws  average_points_scored  
0                              0.672                    9.2  
1                              0.797                   11.7  
2                              0.761                   15.8  
3                              0.651                    8.6  
4                              0.900                   23.2

In [118]:
y = df["average_points_scored"].values

In [123]:
x = df.iloc[:,:-1].values
x

array([[6.80e+00, 2.25e+02, 4.42e-01, 6.72e-01],
       [6.30e+00, 1.80e+02, 4.35e-01, 7.97e-01],
       [6.40e+00, 1.90e+02, 4.56e-01, 7.61e-01],
       [6.20e+00, 1.80e+02, 4.16e-01, 6.51e-01],
       [6.90e+00, 2.05e+02, 4.49e-01, 9.00e-01],
       [6.40e+00, 2.25e+02, 4.31e-01, 7.80e-01],
       [6.30e+00, 1.85e+02, 4.87e-01, 7.71e-01],
       [6.80e+00, 2.35e+02, 4.69e-01, 7.50e-01],
       [6.90e+00, 2.35e+02, 4.35e-01, 8.18e-01],
       [6.70e+00, 2.10e+02, 4.80e-01, 8.25e-01],
       [6.90e+00, 2.45e+02, 5.16e-01, 6.32e-01],
       [6.90e+00, 2.45e+02, 4.93e-01, 7.57e-01],
       [6.30e+00, 1.85e+02, 3.74e-01, 7.09e-01],
       [6.10e+00, 1.85e+02, 4.24e-01, 7.82e-01],
       [6.20e+00, 1.80e+02, 4.41e-01, 7.75e-01],
       [6.80e+00, 2.20e+02, 5.03e-01, 8.80e-01],
       [6.50e+00, 1.94e+02, 5.03e-01, 8.33e-01],
       [7.60e+00, 2.25e+02, 4.25e-01, 5.71e-01],
       [6.30e+00, 2.10e+02, 3.71e-01, 8.16e-01],
       [7.10e+00, 2.40e+02, 5.04e-01, 7.14e-01],
       [6.80e+00, 2.

# rescaled

In [126]:
mu_X = np.mean(x, axis=0)
std_X = np.std(x, axis=0)

rescaled_X = (x-mu_X) / std_X

In [127]:
rescaled_X[:5]

array([[ 0.46843663,  0.50336336, -0.12692668, -0.70404955],
       [-0.63137111, -0.99746237, -0.25187012,  0.55584824],
       [-0.41140956, -0.66394554,  0.12296022,  0.19299768],
       [-0.85133266, -0.99746237, -0.59100234, -0.91571238],
       [ 0.68839818, -0.1636703 , -0.00198323,  1.59400403]])

In [128]:
lr.fit(rescaled_X, y)

In [132]:
sk_lr.fit(rescaled_X, y)

LinearRegression()

In [129]:
lr.coef

array([-1.67779283,  0.28359762,  2.68586629,  1.12816882])

In [133]:
sk_lr.coef_

array([-1.67779283,  0.28359762,  2.68586629,  1.12816882])

In [130]:
lr.intercept

11.790740740740738

In [134]:
sk_lr.intercept_

11.790740740740736