In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
test_df = pd.read_csv("./data/test.csv")
train_df = pd.read_csv("./data/train.csv")

In [6]:
train_df.set_index('PassengerId', inplace=True)
test_df.set_index('PassengerId', inplace=True)

In [7]:
train_index = train_df.index
test_index = test_df.index

In [8]:
y_train_df = train_df.pop("Survived") 

In [9]:
y_train_df.head(3)

PassengerId
1    0
2    1
3    1
Name: Survived, dtype: int64

# Data preproceesing

In [10]:
pd.set_option('display.float_format', lambda x: '%.2f' % x) #소수점 둘째 짜리까지만 표시

In [12]:
test_df.isnull().sum() / len(test_df) * 100#결측치 표시

Pclass      0.00
Name        0.00
Sex         0.00
Age        20.57
SibSp       0.00
Parch       0.00
Ticket      0.00
Fare        0.24
Cabin      78.23
Embarked    0.00
dtype: float64

In [13]:
del test_df["Cabin"] #결측치가 많은 cabin을 날림. 근데 실제로는 cabin에는 많은 정보가 들어가 있음
del train_df["Cabin"]

In [14]:
all_df = train_df.append(test_df)
all_df

Pclass                                               Name  \
PassengerId                                                              
1                 3                            Braund, Mr. Owen Harris   
2                 1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
3                 3                             Heikkinen, Miss. Laina   
4                 1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
5                 3                           Allen, Mr. William Henry   
...             ...                                                ...   
1305              3                                 Spector, Mr. Woolf   
1306              1                       Oliva y Ocana, Dona. Fermina   
1307              3                       Saether, Mr. Simon Sivertsen   
1308              3                                Ware, Mr. Frederick   
1309              3                           Peter, Master. Michael J   

                Sex   Age  SibSp  Parch              Ticket   Fare Embarked  
PassengerId                                                                  
1              male 22.00      1      0           A/5 21171   7.25        S  
2            female 38.00      1      0            PC 17599  71.28        C  
3            female 26.00      0      0    STON/O2. 3101282   7.92        S  
4            female 35.00      1      0              113803  53.10        S  
5              male 35.00      0      0              373450   8.05        S  
...             ...   ...    ...    ...                 ...    ...      ...  
1305           male   NaN      0      0           A.5. 3236   8.05        S  
1306         female 39.00      0      0            PC 17758 108.90        C  
1307           male 38.50      0      0  SOTON/O.Q. 3101262   7.25        S  
1308           male   NaN      0      0              359309   8.05        S  
1309           male   NaN      1      1                2668  22.36        C  

[1309 rows x 9 columns]

In [15]:
del all_df["Name"]
del all_df["Ticket"]

In [16]:
all_df["Sex"] = all_df["Sex"].replace({"male":0,"female":1}) 

In [17]:
all_df["Embarked"].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [18]:
all_df["Embarked"] = all_df["Embarked"].replace({"S":0,"C":1,"Q":2, np.nan:99})
all_df["Embarked"].unique()

array([ 0,  1,  2, 99], dtype=int64)

In [19]:
all_df.head()

Pclass  Sex   Age  SibSp  Parch  Fare  Embarked
PassengerId                                                 
1                 3    0 22.00      1      0  7.25         0
2                 1    1 38.00      1      0 71.28         1
3                 3    1 26.00      0      0  7.92         0
4                 1    1 35.00      1      0 53.10         0
5                 3    0 35.00      0      0  8.05         0

In [22]:
pd.get_dummies(all_df["Embarked"], prefix="embarked")

embarked_0  embarked_1  embarked_2  embarked_99
PassengerId                                                 
1                     1           0           0            0
2                     0           1           0            0
3                     1           0           0            0
4                     1           0           0            0
5                     1           0           0            0
...                 ...         ...         ...          ...
1305                  1           0           0            0
1306                  0           1           0            0
1307                  1           0           0            0
1308                  1           0           0            0
1309                  0           1           0            0

[1309 rows x 4 columns]

In [23]:
matrix_df = pd.merge(
    all_df, pd.get_dummies(all_df["Embarked"], prefix="embarked"), 
    left_index=True, right_index=True)
matrix_df.head()

Pclass  Sex   Age  SibSp  Parch  Fare  Embarked  embarked_0  \
PassengerId                                                                
1                 3    0 22.00      1      0  7.25         0           1   
2                 1    1 38.00      1      0 71.28         1           0   
3                 3    1 26.00      0      0  7.92         0           1   
4                 1    1 35.00      1      0 53.10         0           1   
5                 3    0 35.00      0      0  8.05         0           1   

             embarked_1  embarked_2  embarked_99  
PassengerId                                       
1                     0           0            0  
2                     1           0            0  
3                     0           0            0  
4                     0           0            0  
5                     0           0            0

In [24]:
matrix_df.corr()

Pclass   Sex   Age  SibSp  Parch  Fare  Embarked  embarked_0  \
Pclass         1.00 -0.12 -0.41   0.06   0.02 -0.56     -0.05        0.10   
Sex           -0.12  1.00 -0.06   0.11   0.21  0.19      0.07       -0.12   
Age           -0.41 -0.06  1.00  -0.24  -0.15  0.18      0.07       -0.08   
SibSp          0.06  0.11 -0.24   1.00   0.37  0.16     -0.03        0.08   
Parch          0.02  0.21 -0.15   0.37   1.00  0.22     -0.03        0.07   
Fare          -0.56  0.19  0.18   0.16   0.22  1.00      0.05       -0.17   
Embarked      -0.05  0.07  0.07  -0.03  -0.03  0.05      1.00       -0.21   
embarked_0     0.10 -0.12 -0.08   0.08   0.07 -0.17     -0.21        1.00   
embarked_1    -0.27  0.07  0.09  -0.05  -0.01  0.29      0.06       -0.78   
embarked_2     0.23  0.09 -0.02  -0.05  -0.10 -0.13      0.12       -0.49   
embarked_99   -0.06  0.05  0.06  -0.02  -0.02  0.04      0.99       -0.06   

             embarked_1  embarked_2  embarked_99  
Pclass            -0.27        0.23        -0.06  
Sex                0.07        0.09         0.05  
Age                0.09       -0.02         0.06  
SibSp             -0.05       -0.05        -0.02  
Parch             -0.01       -0.10        -0.02  
Fare               0.29       -0.13         0.04  
Embarked           0.06        0.12         0.99  
embarked_0        -0.78       -0.49        -0.06  
embarked_1         1.00       -0.16        -0.02  
embarked_2        -0.16        1.00        -0.01  
embarked_99       -0.02       -0.01         1.00

In [25]:
all_df.groupby("Pclass")["Age"].mean()

Pclass
1   39.16
2   29.51
3   24.82
Name: Age, dtype: float64

In [26]:
all_df.groupby("Sex")["Age"].mean()

Sex
0   30.59
1   28.69
Name: Age, dtype: float64

In [27]:
# all_df.loc[]
all_df.loc[ 
    (all_df["Pclass"] == 1) & (all_df["Age"].isnull()) , "Age"]

PassengerId
32     NaN
56     NaN
65     NaN
167    NaN
169    NaN
186    NaN
257    NaN
271    NaN
285    NaN
296    NaN
299    NaN
307    NaN
335    NaN
352    NaN
376    NaN
458    NaN
476    NaN
508    NaN
528    NaN
558    NaN
603    NaN
634    NaN
670    NaN
712    NaN
741    NaN
767    NaN
794    NaN
816    NaN
840    NaN
850    NaN
914    NaN
933    NaN
1038   NaN
1040   NaN
1060   NaN
1083   NaN
1097   NaN
1158   NaN
1182   NaN
Name: Age, dtype: float64

In [28]:
all_df.loc[(all_df["Pclass"] == 1) & (
        all_df["Age"].isnull()), "Age"] = 39.16
all_df.loc[ (
    all_df["Pclass"] == 2) & all_df["Age"].isnull() , "Age"] = 29.51
all_df.loc[ ( all_df["Pclass"] == 3) & all_df["Age"].isnull(), "Age"] = 24.82

In [29]:
all_df.isnull().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        1
Embarked    0
dtype: int64

In [30]:
all_df.groupby("Pclass")["Fare"].mean()

Pclass
1   87.51
2   21.18
3   13.30
Name: Fare, dtype: float64

In [31]:
all_df[all_df["Fare"].isnull()]

Pclass  Sex   Age  SibSp  Parch  Fare  Embarked
PassengerId                                                 
1044              3    0 60.50      0      0   NaN         0

In [32]:
all_df.loc[all_df["Fare"].isnull(), "Fare"] = 13.30

In [33]:
del all_df["Embarked"]

In [34]:
all_df["Pclass"] = all_df["Pclass"].replace({1:"A",2:"B",3:"C"})

In [35]:
all_df = pd.get_dummies(all_df)
all_df.head()

Sex   Age  SibSp  Parch  Fare  Pclass_A  Pclass_B  Pclass_C
PassengerId                                                             
1              0 22.00      1      0  7.25         0         0         1
2              1 38.00      1      0 71.28         1         0         0
3              1 26.00      0      0  7.92         0         0         1
4              1 35.00      1      0 53.10         1         0         0
5              0 35.00      0      0  8.05         0         0         1

In [36]:
all_df = pd.merge(
    all_df, matrix_df[["embarked_0", "embarked_1", "embarked_2", "embarked_99"]], 
    left_index=True, right_index=True)

In [38]:
all_df

Sex   Age  SibSp  Parch   Fare  Pclass_A  Pclass_B  Pclass_C  \
PassengerId                                                                 
1              0 22.00      1      0   7.25         0         0         1   
2              1 38.00      1      0  71.28         1         0         0   
3              1 26.00      0      0   7.92         0         0         1   
4              1 35.00      1      0  53.10         1         0         0   
5              0 35.00      0      0   8.05         0         0         1   
...          ...   ...    ...    ...    ...       ...       ...       ...   
1305           0 24.82      0      0   8.05         0         0         1   
1306           1 39.00      0      0 108.90         1         0         0   
1307           0 38.50      0      0   7.25         0         0         1   
1308           0 24.82      0      0   8.05         0         0         1   
1309           0 24.82      1      1  22.36         0         0         1   

             embarked_0  embarked_1  embarked_2  embarked_99  
PassengerId                                                   
1                     1           0           0            0  
2                     0           1           0            0  
3                     1           0           0            0  
4                     1           0           0            0  
5                     1           0           0            0  
...                 ...         ...         ...          ...  
1305                  1           0           0            0  
1306                  0           1           0            0  
1307                  1           0           0            0  
1308                  1           0           0            0  
1309                  0           1           0            0  

[1309 rows x 12 columns]

In [40]:
train_df = all_df[all_df.index.isin(train_index)]
test_df = all_df[all_df.index.isin(test_index)]

# Build model

In [44]:
x_data = train_df.values
y_data = y_train_df.values

In [45]:
x_data.shape, y_data.shape

((891, 12), (891,))

In [46]:
y_data

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [47]:
from sklearn.linear_model import LogisticRegression
cls = LogisticRegression()
cls.fit(x_data,y_data)

C:\Users\1004\Anaconda3\envs\human\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [48]:
cls.intercept_

array([0.18004232])

In [49]:
cls.coef_

array([[ 2.60489281e+00, -4.12158094e-02, -3.26991215e-01,
        -8.24646191e-02,  2.38742501e-03,  1.11393614e+00,
         1.45014357e-01, -1.09217032e+00, -2.11593274e-01,
         2.13076311e-01,  9.90664630e-02,  6.62306804e-02]])

In [50]:
cls.predict(test_df.values)

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [51]:
test_df.index

Int64Index([ 892,  893,  894,  895,  896,  897,  898,  899,  900,  901,
            ...
            1300, 1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309],
           dtype='int64', name='PassengerId', length=418)

In [52]:
x_test = test_df.values
y_test =cls.predict(x_test)
y_test

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [53]:
result = np.concatenate( (test_index.values.reshape(-1,1),
                 cls.predict(x_test).reshape(-1,1)  ) , axis=1)
result[:5]

array([[892,   0],
       [893,   0],
       [894,   0],
       [895,   0],
       [896,   1]], dtype=int64)

In [54]:
df_submssion =pd.DataFrame(result, columns=["PassengerId","Survived"])
df_submssion

PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [55]:
df_submssion.to_csv("submission_result.csv",index=False)